name: DEV CI/CD Pipeline

on:
  push:
    branches: [ develop ]  # develop ë¸Œëœì¹˜ì— pushê°€ ì¼ì–´ë‚  ë•Œ ì‹¤í–‰
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - deploy
          - stop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ì €ì¥ì†Œ ì½”ë“œ ì²´í¬ì•„ì›ƒ
      - uses: actions/checkout@v4

      # JDK 17 ì„¤ì •
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      # application.yml íŒŒì¼ ìƒì„±
      - name: Make application-dev.yml
        run: |
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./application-dev.yml
        shell: bash

      # serviceAccountKey.json íŒŒì¼ ìƒì„±
      - name: Make serviceAccountKey.json
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' > ./src/main/resources/serviceAccountKey.json
        shell: bash

      # Gradleë¡œ ë¹Œë“œ
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # Docker ì´ë¯¸ì§€ ë¹Œë“œ ë° í‘¸ì‹œ (ğŸš¨ `--build-arg` ì¶”ê°€!)
      - name: Docker build & push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build --no-cache -t ${{ secrets.DOCKER_REPO }}-dev:${{ github.sha }}  .
          docker push ${{ secrets.DOCKER_REPO }}-dev:${{ github.sha }} 

      # ì„œë²„ ë°°í¬
      - name: Deploy to server with Docker
        uses: appleboy/ssh-action@master
        env:
          ACTION: ${{ github.event.inputs.action || 'deploy' }}
          IMAGE_TAG: ${{ github.sha }}
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE_TAG
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}-dev:$IMAGE_TAG
            cd /root
            
            if [ "$ACTION" == "deploy" ]; then
                docker compose down --remove-orphans || true
                IMAGE_TAG=$IMAGE_TAG docker compose up -d --force-recreate
            
            elif [ "$ACTION" == "stop" ]; then
                sudo docker compose down
                echo "Dev Environment Stopped"
            fi
            
            sudo docker image prune -a --filter "until=72h" -f
            sudo docker container prune --filter "until=72h" -f
            sudo docker network prune --filter "until=72h" -f
      # jar íŒŒì¼ëª… í™•ì¸
      - name: Show built files
        run: |
          ls -alh build/libs